spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

--- # local

spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:

  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: embedded

logging:
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error
    org.hibernate,SQL: debug
    org.hibernate.type: trace # 2.x
#    org.hibernate.orm.jdbc.bind: trace  # 3.x


--- # dev

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql:1237.0.0.1:3306/watermelon
      username: testadmin
      password: password

  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always